/*
* Enum class representing a key on the keyboard.
*/

#ifndef PCG_KEY_H
#define PCG_KEY_H

#include <type_traits>

namespace pcg
{
    enum class Key
    {
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Comma,
        Period,
        Escape,
        LeftControl,
        RightControl,
        LeftShift,
        RightShift,
        Tab,
        CapsLock,
        Up,
        Down,
        Left,
        Right,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        Semicolon,
        Equal,
        Slash,
        Minus,
        Apostrophe,
        Space,
        LeftBracket,
        RightBracket,
        Backslash,
        GraveAccent,
        Enter,
        Backspace,
        Insert,
        Delete,
        PageUp,
        PageDown,
        Home,
        End,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        KeypadDecimal,
        KeypadDivide,
        KeypadMultiply,
        KeypadSubtract,
        KeypadAdd,
        KeypadEnter,
        KeypadEqual,
        LeftAlt,
        RightAlt,
        Last,
        Unknown
    };

    using KeyIndexType = std::underlying_type<Key>::type;

    KeyIndexType GetKeyIndex(Key key);
}

#endif
